export const dataverseEntitySet = {
  Sede: "crf1_sedes",
  Area: "crf1_areas",
  Bodega: "crf1_bodegas",
  Ubicacion: "crf1_ubicaciones",
  Empleado: "crf1_empleados",
  ItemDotacion: "crf1_itemdotacions",
  Talla: "crf1_tallas",
  Proveedor: "crf1_proveedors",
  CentroCosto: "crf1_centrocostos",
  KitDotacion: "crf1_kitdotacions",
  KitDotacionItem: "crf1_kitdotacionitems",
  PedidoDotacion: "crf1_pedidodotacions",
  PedidoDotacionDetalle: "crf1_pedidodotaciondetalles",
  EntregaDotacion: "crf1_entregadotacions",
  HistorialEvento: "crf1_historialeventos",
  Inventario: "crf1_inventarios",
  MovimientoInventario: "crf1_movimientoinventarios",
  InspeccionCalidad: "crf1_inspeccioncalidads",
  DefectoCalidad: "crf1_defectocalidads",
  ChecklistCalidad: "crf1_checklistcalidads",
  TipoDefecto: "crf1_tipodefectos",
  Severidad: "crf1_severidads",
  CriterioChecklist: "crf1_criteriochecklists",
  Equipo: "crf1_equipos",
  TicketMantenimiento: "crf1_ticketmantenimientos",
  ActividadMantenimiento: "crf1_actividadmantenimientos",
  PlanPreventivo: "crf1_planpreventivos",
  IntegrationRequest: "crf1_integrationrequests",
  Annotation: "annotations",
} as const;

export const dataverseField = {
  id: "crf1_id",
  sedeId: "crf1_sedeid",
  estado: "crf1_estado",
  createdOn: "createdon",
  modifiedOn: "modifiedon",
};
